one_word_furniture = {
"accubita",
"armchair",
"armchairs",
"barstool",
"barstools",
"bassinet",
"bassinets",
"bed",
"bedframe",
"bedframes",
"bedside",
"beds",
"bedsides",
"bench",
"benches",
"bergere",
"bergeres",
"bin",
"bins",
"bookcase",
"bookcases",
"bookshelf",
"bookshelves",
"breakfront",
"breakfronts",
"buffet",
"buffets",
"bureau",
"bureaus",
"cabinet",
"cabinets",
"canape",
"carpet",
"carpets",
"chair",
"chairs",
"chandelier",
"chandeliers",
"chest",
"chests",
"clock",
"clocks",
"console",
"consoles",
"cot",
"cots",
"couch",
"couches",
"countertop",
"countertops",
"cradle",
"cradles",
"credenza",
"credenzas",
"crib",
"cribs",
"cubbies",
"cupboard",
"cupboards",
"curio",
"curios",
"curtain",
"curtains",
"cushion",
"cushions",
"desk",
"desks",
"divan",
"divans",
"doublebed",
"doublebeds",
"drapery",
"draperies",
"drapes",
"dresser",
"dressers",
"drawer",
"drawers",
"easel",
"fauteuil",
"footrest",
"footstool",
"furnishings",
"furnishing",
"futon",
"futons",
"hammock",
"hammocks",
"hassock",
"headboard",
"headboards",
"highchair",
"highchairs",
"hutch",
"hutches",
"island",
"islands",
"lamp",
"lamps",
"light",
"lights",
"lintel",
"lintels",
"lounger",
"loungers",
"mantle",
"mantles",
"mattress",
"mattresses",
"mirror",
"mirrors",
"nightstand",
"nightstands",
"officer",
"ottoman",
"ottomans",
"pantry",
"pew",
"pillow",
"pillows",
"poufy",
"rack",
"recliner",
"recliners",
"recyclers",
"rug",
"rugs",
"sconce",
"screen",
"seat",
"seats",
"secretary",
"settee",
"shelf",
"shelves",
"sideboard",
"sofa",
"sofas",
"stool",
"stools",
"table",
"tables",
"tansu",
"throne",
"tuffet",
"valet",
"vanity",
"vitrine",
"wardrobe",
"waterbed"
}

two_word_furniture = {
    "accent chair",
    "accent chairs",
    "arm chair",
    "arm chairs",
    "bar chair",
    "bar chairs",
    "bar stool",
    "bar stools",
    "bed table",
    "bed tables",
    "bedside table",
    "bedside tables",
    "bentwood rocker",
    "bentwood rockers",
    "bunk bed",
    "bunk beds",
    "cabinet handles",
    "cabinet handles",
    "cabinet knobs",
    "cabinet knobs",
    "cabinet locks",
    "cabinet locks",
    "cabinet organizer",
    "cabinet organizers",
    "canopy bed",
    "canopy beds",
    "card table",
    "card tables",
    "chaise lounge",
    "chaise lounges",
    "chest drawers",
    "chest drawers",
    "china cabinet",
    "china cabinets",
    "clothes valet",
    "clothes valets",
    "coffee table",
    "coffee tables",
    "compost bin",
    "compost bins",
    "computer chair",
    "computer chairs",
    "computer desk",
    "computer desks",
    "console table",
    "console tables",
    "deck chair",
    "deck chairs",
    "desk chair",
    "desk chairs",
    "desk lamp",
    "desk lamps",
    "director chair",
    "director chairs",
    "dining chair",
    "dining chairs",
    "dining table",
    "dining tables",
    "display cabinet",
    "display cabinets",
    "double bed",
    "double beds",
    "dresser mirror",
    "dresser mirrors",
    "dresser set",
    "dresser sets",
    "easy chair",
    "easy chairs",
    "end table",
    "end tables",
    "fainting couch",
    "fainting couches",
    "file cabinet",
    "file cabinets",
    "file drawer",
    "file drawers",
    "floor lamp",
    "floor lamps",
    "folding chair",
    "folding chairs",
    "folding screen",
    "folding screens",
    "foot rest",
    "foot rests",
    "foot stool",
    "foot stools",
    "furniture covers",
    "furniture covers",
    "garden bench",
    "garden benches",
    "garden chair",
    "garden chairs",
    "garden furniture",
    "garden furniture",
    "garden lounger",
    "garden loungers",
    "garden swing",
    "garden swings",
    "garden table",
    "garden tables",
    "garden umbrella",
    "garden umbrellas",
    "gateleg table",
    "gateleg tables",
    "gift card",
    "gift cards",
    "glider rocker",
    "glider rockers",
    "grandfather clock",
    "grandfather clocks",
    "hall tree",
    "hall trees",
    "hat stand",
    "hat stands",
    "head board",
    "head boards",
    "hope chest",
    "hope chests",
    "kitchen chair",
    "kitchen chairs",
    "kitchen island",
    "kitchen islands",
    "ladderback chair",
    "ladderback chairs",
    "lawn chair",
    "lawn chairs",
    "lift chair",
    "lift chairs",
    "lounge chair",
    "lounge chairs",
    "love seat",
    "love seats",
    "mattress king",
    "mattress kings",
    "mattress queen",
    "mattress queens",
    "murphy bed",
    "murphy beds",
    "night stand",
    "night stands",
    "office cabinet",
    "office cabinets",
    "office chair",
    "office chairs",
    "office desk",
    "office desks",
    "office table",
    "office tables",
    "patio chair",
    "patio chairs",
    "patio cushions",
    "patio cushions",
    "patio furniture",
    "patio furniture",
    "patio heaters",
    "patio heaters",
    "patio set",
    "patio sets",
    "patio table",
    "patio tables",
    "patio umbrella",
    "patio umbrellas",
    "picnic table",
    "picnic tables",
    "piano bench",
    "piano benches",
    "porch swing",
    "porch swings",
    "room divider",
    "room dividers",
    "sectional sofa",
    "sectional sofas",
    "shoji screen",
    "shoji screens",
    "side board",
    "side boards",
    "side chair",
    "side chairs",
    "sleeper sofa",
    "sleeper sofas",
    "sofa bed",
    "sofa beds",
    "standing desk",
    "standing desks",
    "study desk",
    "study desks",
    "study table",
    "study tables",
    "table lamp",
    "table lamps",
    "tea cart",
    "tea carts",
    "throw rug",
    "throw rugs",
    "trundle bed",
    "trundle beds",
    "vanity chair",
    "vanity chairs",
    "vanity mirror",
    "vanity mirrors",
    "vanity set",
    "vanity sets",
    "vanity stool",
    "vanity stools",
    "vanity table",
    "vanity tables",
    "venetian blinds",
    "venetian blinds",
    "water bed",
    "water beds",
    "wing chair",
    "wing chairs",
    "work table",
    "work tables",
    "writing desk",
    "writing desks",
    "waste basket",
    "waste baskets"
}


three_word_furniture = {
"bean bag chair",
"bean bag chairs",
"bedside table lamp",
"bedside table lamps",
"breakfast bar stool",
"breakfast bar stools",
"coffee table ottoman",
"coffee table ottomans",
"computer gaming desk",
"computer gaming desks",
"corner display cabinet",
"corner display cabinets",
"dining room table",
"dining room tables",
"entryway storage bench",
"entryway storage benches",
"folding camping chair",
"folding camping chairs",
"four poster bed",
"four poster beds",
"kitchen island cart",
"kitchen island carts",
"ottoman storage bench",
"ottoman storage benches",
"patio dining set",
"patio dining sets",
"pedestal dining table",
"pedestal dining tables",
"rocking chair cushion",
"rocking chair cushions",
"shoe storage cabinet",
"shoe storage cabinets",
"standing desk converter",
"standing desk converters",
"study desk lamp",
"study desk lamps",
"tv entertainment center",
"tv entertainment centers"

}